spring:
  application:
    name: Inventory
  datasource:
    url: jdbc:postgresql://localhost:5555/inventory
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
varejo:
  config:
    clients:
      catalog-service:
        url: "http://localhost:8081/v1/api/varejo/products"
    kafka:
      server-url: "http://localhost:29092"
      topics:
        inventory-events: "inventory-events"

server:
  port: 8082
